// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

package task

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Contact struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SearchAt             string   `protobuf:"bytes,8,opt,name=search_at,json=searchAt,proto3" json:"search_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Number               string   `protobuf:"bytes,7,opt,name=number,proto3" json:"number,omitempty"`
	Age                  string   `protobuf:"bytes,9,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Contact) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Contact) GetSearchAt() string {
	if m != nil {
		return m.SearchAt
	}
	return ""
}

func (m *Contact) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Contact) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

type MakeDoneRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeDoneRequest) Reset()         { *m = MakeDoneRequest{} }
func (m *MakeDoneRequest) String() string { return proto.CompactTextString(m) }
func (*MakeDoneRequest) ProtoMessage()    {}
func (*MakeDoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{1}
}

func (m *MakeDoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDoneRequest.Unmarshal(m, b)
}
func (m *MakeDoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDoneRequest.Marshal(b, m, deterministic)
}
func (m *MakeDoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDoneRequest.Merge(m, src)
}
func (m *MakeDoneRequest) XXX_Size() int {
	return xxx_messageInfo_MakeDoneRequest.Size(m)
}
func (m *MakeDoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDoneRequest proto.InternalMessageInfo

func (m *MakeDoneRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateTaskRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Task                 *Contact `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{2}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTaskRequest) GetTask() *Contact {
	if m != nil {
		return m.Task
	}
	return nil
}

type SearchTaskRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Task                 *Contact `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTaskRequest) Reset()         { *m = SearchTaskRequest{} }
func (m *SearchTaskRequest) String() string { return proto.CompactTextString(m) }
func (*SearchTaskRequest) ProtoMessage()    {}
func (*SearchTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{3}
}

func (m *SearchTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTaskRequest.Unmarshal(m, b)
}
func (m *SearchTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTaskRequest.Marshal(b, m, deterministic)
}
func (m *SearchTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTaskRequest.Merge(m, src)
}
func (m *SearchTaskRequest) XXX_Size() int {
	return xxx_messageInfo_SearchTaskRequest.Size(m)
}
func (m *SearchTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTaskRequest proto.InternalMessageInfo

func (m *SearchTaskRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchTaskRequest) GetTask() *Contact {
	if m != nil {
		return m.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{4}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{5}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type CountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountRequest) Reset()         { *m = CountRequest{} }
func (m *CountRequest) String() string { return proto.CompactTextString(m) }
func (*CountRequest) ProtoMessage()    {}
func (*CountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{6}
}

func (m *CountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountRequest.Unmarshal(m, b)
}
func (m *CountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountRequest.Marshal(b, m, deterministic)
}
func (m *CountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountRequest.Merge(m, src)
}
func (m *CountRequest) XXX_Size() int {
	return xxx_messageInfo_CountRequest.Size(m)
}
func (m *CountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountRequest proto.InternalMessageInfo

type GetAllResponse struct {
	Tasks                []*Contact `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{7}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetTasks() []*Contact {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type FlagResponse struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlagResponse) Reset()         { *m = FlagResponse{} }
func (m *FlagResponse) String() string { return proto.CompactTextString(m) }
func (*FlagResponse) ProtoMessage()    {}
func (*FlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{8}
}

func (m *FlagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlagResponse.Unmarshal(m, b)
}
func (m *FlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlagResponse.Marshal(b, m, deterministic)
}
func (m *FlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlagResponse.Merge(m, src)
}
func (m *FlagResponse) XXX_Size() int {
	return xxx_messageInfo_FlagResponse.Size(m)
}
func (m *FlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlagResponse proto.InternalMessageInfo

func (m *FlagResponse) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

type SearchTaskResponse struct {
	Tasks                []*Contact `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchTaskResponse) Reset()         { *m = SearchTaskResponse{} }
func (m *SearchTaskResponse) String() string { return proto.CompactTextString(m) }
func (*SearchTaskResponse) ProtoMessage()    {}
func (*SearchTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{9}
}

func (m *SearchTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTaskResponse.Unmarshal(m, b)
}
func (m *SearchTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTaskResponse.Marshal(b, m, deterministic)
}
func (m *SearchTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTaskResponse.Merge(m, src)
}
func (m *SearchTaskResponse) XXX_Size() int {
	return xxx_messageInfo_SearchTaskResponse.Size(m)
}
func (m *SearchTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTaskResponse proto.InternalMessageInfo

func (m *SearchTaskResponse) GetTasks() []*Contact {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type CountTaskResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountTaskResponse) Reset()         { *m = CountTaskResponse{} }
func (m *CountTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CountTaskResponse) ProtoMessage()    {}
func (*CountTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{10}
}

func (m *CountTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountTaskResponse.Unmarshal(m, b)
}
func (m *CountTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountTaskResponse.Marshal(b, m, deterministic)
}
func (m *CountTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountTaskResponse.Merge(m, src)
}
func (m *CountTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CountTaskResponse.Size(m)
}
func (m *CountTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountTaskResponse proto.InternalMessageInfo

func (m *CountTaskResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Contact)(nil), "task.Contact")
	proto.RegisterType((*MakeDoneRequest)(nil), "task.MakeDoneRequest")
	proto.RegisterType((*UpdateTaskRequest)(nil), "task.UpdateTaskRequest")
	proto.RegisterType((*SearchTaskRequest)(nil), "task.SearchTaskRequest")
	proto.RegisterType((*DeleteTaskRequest)(nil), "task.DeleteTaskRequest")
	proto.RegisterType((*GetAllRequest)(nil), "task.GetAllRequest")
	proto.RegisterType((*CountRequest)(nil), "task.CountRequest")
	proto.RegisterType((*GetAllResponse)(nil), "task.GetAllResponse")
	proto.RegisterType((*FlagResponse)(nil), "task.FlagResponse")
	proto.RegisterType((*SearchTaskResponse)(nil), "task.SearchTaskResponse")
	proto.RegisterType((*CountTaskResponse)(nil), "task.CountTaskResponse")
}

func init() {
	proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15)
}

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x89, 0x93, 0xc6, 0xd3, 0x26, 0x25, 0x43, 0x44, 0x57, 0x41, 0x48, 0xe9, 0xf6, 0x52,
	0x2e, 0x91, 0x28, 0xe2, 0x40, 0x39, 0x59, 0xa9, 0xc2, 0x89, 0x4b, 0x0a, 0x67, 0xb4, 0xb5, 0x07,
	0x63, 0xc5, 0xb1, 0x83, 0xbd, 0xe1, 0x1b, 0xf9, 0x25, 0x6e, 0x68, 0x67, 0xd7, 0x8d, 0x83, 0x29,
	0xa2, 0xb7, 0x9d, 0x37, 0xf3, 0x66, 0xe6, 0xcd, 0xb3, 0x0c, 0xc3, 0xa8, 0xc8, 0xb5, 0x8a, 0xf4,
	0x7c, 0x5b, 0x16, 0xba, 0x40, 0x5f, 0xab, 0x6a, 0x2d, 0x7f, 0x7a, 0x70, 0xb4, 0xb0, 0x38, 0x8e,
	0xa0, 0x93, 0xc6, 0xc2, 0x9b, 0x79, 0x97, 0xc1, 0xaa, 0x93, 0xc6, 0xf8, 0x12, 0x60, 0xb7, 0x8d,
	0x95, 0xa6, 0xf8, 0x8b, 0xd2, 0xa2, 0xcb, 0x78, 0xe0, 0x90, 0x50, 0xe3, 0x0b, 0x08, 0x2a, 0x52,
	0x65, 0xf4, 0xcd, 0x64, 0x07, 0x9c, 0x1d, 0x58, 0x20, 0xd4, 0x86, 0x1b, 0x53, 0x46, 0x8e, 0xeb,
	0x5b, 0xae, 0x43, 0x42, 0x8d, 0x08, 0x7e, 0xae, 0x36, 0x24, 0x7a, 0x9c, 0xe0, 0x37, 0x4e, 0xa0,
	0x47, 0x1b, 0x95, 0x66, 0xa2, 0xcf, 0xa0, 0x0d, 0xf0, 0x39, 0xf4, 0xf3, 0xdd, 0xe6, 0x8e, 0x4a,
	0x71, 0xc4, 0xb0, 0x8b, 0xf0, 0x29, 0x74, 0x55, 0x42, 0x22, 0x60, 0xd0, 0x3c, 0xe5, 0x39, 0x9c,
	0x7e, 0x54, 0x6b, 0xba, 0x29, 0x72, 0x5a, 0xd1, 0xf7, 0x1d, 0x55, 0x4d, 0x45, 0xbe, 0x51, 0x24,
	0x97, 0x30, 0xfe, 0xcc, 0xfb, 0x7f, 0x52, 0xd5, 0xba, 0x5d, 0xd4, 0x65, 0xd9, 0xe7, 0xc0, 0xa7,
	0x11, 0x9d, 0x99, 0x77, 0x79, 0x7c, 0x35, 0x9c, 0x9b, 0x60, 0xee, 0x6e, 0xb4, 0xb2, 0x57, 0x5b,
	0xc2, 0xf8, 0x96, 0x95, 0xfe, 0xbd, 0x4f, 0xf0, 0xbf, 0x7d, 0x2e, 0x60, 0x7c, 0xc3, 0x37, 0xf9,
	0xc7, 0x3e, 0xf2, 0x14, 0x86, 0x1f, 0x48, 0x87, 0x59, 0xe6, 0x0a, 0xe4, 0x08, 0x4e, 0x16, 0xc5,
	0x2e, 0xd7, 0x75, 0xfc, 0x16, 0x46, 0x75, 0x41, 0xb5, 0x2d, 0xf2, 0x8a, 0xf0, 0x02, 0x7a, 0xa6,
	0x7f, 0x25, 0xbc, 0x59, 0xb7, 0x3d, 0xdb, 0xe6, 0xa4, 0x84, 0x93, 0x65, 0xa6, 0x92, 0x7b, 0x12,
	0x82, 0xff, 0x35, 0x53, 0x09, 0x4f, 0x1e, 0xac, 0xf8, 0x2d, 0xdf, 0x01, 0x36, 0x85, 0x3e, 0xa6,
	0xfd, 0x2b, 0x18, 0xf3, 0x96, 0x07, 0xcc, 0x09, 0xf4, 0x22, 0x03, 0x3a, 0x79, 0x36, 0xb8, 0xfa,
	0xd5, 0x31, 0xd6, 0xe5, 0x2a, 0x49, 0xf3, 0xe4, 0x96, 0xca, 0x1f, 0x69, 0x44, 0xf8, 0x1a, 0x60,
	0x51, 0x92, 0xb3, 0x0a, 0x0f, 0x47, 0x4c, 0xd1, 0x86, 0xcd, 0xf5, 0xe5, 0x13, 0x7c, 0x0f, 0xb0,
	0x77, 0x17, 0xcf, 0x6c, 0x4d, 0xcb, 0xef, 0x07, 0xc8, 0x21, 0xc0, 0x5e, 0x69, 0x4d, 0x6e, 0x99,
	0x3c, 0x15, 0xed, 0x44, 0x73, 0xfe, 0xde, 0xcd, 0xba, 0x45, 0xcb, 0xdf, 0x07, 0xe6, 0x5f, 0x43,
	0x70, 0x7f, 0x2e, 0xc4, 0x5a, 0xee, 0xde, 0xe5, 0xe9, 0x59, 0x03, 0xfb, 0x63, 0xf0, 0x35, 0x1c,
	0xdb, 0x0f, 0xc0, 0xe0, 0x15, 0x3e, 0xb3, 0x95, 0x07, 0x1f, 0xcd, 0x74, 0x72, 0x08, 0xd6, 0xdc,
	0xbb, 0x3e, 0xff, 0x0d, 0xde, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x40, 0x72, 0xf3, 0x93, 0x1e,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ManagingServiceClient is the client API for ManagingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagingServiceClient interface {
	CreateTask(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*FlagResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error)
	SearchTask(ctx context.Context, in *SearchTaskRequest, opts ...grpc.CallOption) (*SearchTaskResponse, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error)
	CountTask(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountTaskResponse, error)
	GetAllTasks(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type managingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagingServiceClient(cc grpc.ClientConnInterface) ManagingServiceClient {
	return &managingServiceClient{cc}
}

func (c *managingServiceClient) CreateTask(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) SearchTask(ctx context.Context, in *SearchTaskRequest, opts ...grpc.CallOption) (*SearchTaskResponse, error) {
	out := new(SearchTaskResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/SearchTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) CountTask(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountTaskResponse, error) {
	out := new(CountTaskResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/CountTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) GetAllTasks(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/GetAllTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagingServiceServer is the server API for ManagingService service.
type ManagingServiceServer interface {
	CreateTask(context.Context, *Contact) (*FlagResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*FlagResponse, error)
	SearchTask(context.Context, *SearchTaskRequest) (*SearchTaskResponse, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*FlagResponse, error)
	CountTask(context.Context, *CountRequest) (*CountTaskResponse, error)
	GetAllTasks(context.Context, *GetAllRequest) (*GetAllResponse, error)
}

// UnimplementedManagingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedManagingServiceServer struct {
}

func (*UnimplementedManagingServiceServer) CreateTask(ctx context.Context, req *Contact) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedManagingServiceServer) UpdateTask(ctx context.Context, req *UpdateTaskRequest) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (*UnimplementedManagingServiceServer) SearchTask(ctx context.Context, req *SearchTaskRequest) (*SearchTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTask not implemented")
}
func (*UnimplementedManagingServiceServer) DeleteTask(ctx context.Context, req *DeleteTaskRequest) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (*UnimplementedManagingServiceServer) CountTask(ctx context.Context, req *CountRequest) (*CountTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountTask not implemented")
}
func (*UnimplementedManagingServiceServer) GetAllTasks(ctx context.Context, req *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTasks not implemented")
}

func RegisterManagingServiceServer(s *grpc.Server, srv ManagingServiceServer) {
	s.RegisterService(&_ManagingService_serviceDesc, srv)
}

func _ManagingService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).CreateTask(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_SearchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).SearchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/SearchTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).SearchTask(ctx, req.(*SearchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_CountTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).CountTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/CountTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).CountTask(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_GetAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).GetAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/GetAllTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).GetAllTasks(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task.ManagingService",
	HandlerType: (*ManagingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _ManagingService_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _ManagingService_UpdateTask_Handler,
		},
		{
			MethodName: "SearchTask",
			Handler:    _ManagingService_SearchTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _ManagingService_DeleteTask_Handler,
		},
		{
			MethodName: "CountTask",
			Handler:    _ManagingService_CountTask_Handler,
		},
		{
			MethodName: "GetAllTasks",
			Handler:    _ManagingService_GetAllTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contact.proto",
}
